apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: od9crvv11-nodejs
  janus-idp.io/tekton: od9crvv11-nodejs
  backstage.io/kubernetes-id: od9crvv11-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: od9crvv11-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
