apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: od9crvv11-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: od9crvv11-nodejs 
  name: od9crvv11-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: od9crvv11-nodejs 
